docs/DeveloperGuide.md

docs: update DG product scope

---

src/main/java/seedu/smartnus/model/util/SampleDataUtil.java

Add tf sample questions.
Reminder: For the sample questions to be updated you have to delete `data/smartnus.json`

Add tf sample questions

---

docs/DeveloperGuide.md

Update DG with basic parser logic

Update DG with basic parser logic

---

docs/UserGuide.md

Added some todos for further standardising of commands for the respective authors.

Fix quiz hyperlinks, standardise title of headers to be imperatives

---

src/main/java/seedu/smartnus/ui/HelpWindow.java

Fix user guide url.
Resolves https://github.com/AY2122S1-CS2103T-F12-1/tp/issues/123

Fix user guide url

---

src/main/java/seedu/smartnus/MainApp.java

Update version number

---

docs/DeveloperGuide.md
docs/index.md

Updated title and acknowledgements of home page

Update website home page

---

src/main/java/seedu/smartnus/logic/parser/quiz/AnswerMcqCommandParser.java
src/main/java/seedu/smartnus/logic/parser/quiz/AnswerSaqCommandParser.java
src/main/java/seedu/smartnus/logic/parser/quiz/AnswerTfqCommandParser.java
src/main/java/seedu/smartnus/model/quiz/QuizManager.java
src/test/java/seedu/smartnus/logic/parser/quiz/AnswerMcqCommandParserTest.java
src/test/java/seedu/smartnus/logic/parser/quiz/AnswerSaqCommandParserTest.java
src/test/java/seedu/smartnus/logic/parser/quiz/AnswerTfqCommandParserTest.java

Fix continued validation during quiz after a question is answered.
Resolves https://github.com/AY2122S1-CS2103T-F12-1/tp/issues/158

Fix continued validation

---

docs/UserGuide.md
src/main/java/seedu/smartnus/logic/commands/ListCommand.java

Fix various issues pointed out in PE-D

Fix various issues pointed out in PE-D

---

src/main/java/seedu/smartnus/logic/parser/ParserUtil.java
src/test/java/seedu/smartnus/logic/parser/ParserUtilTest.java

Accept lowercase for answer in tfq

---

src/main/java/seedu/smartnus/logic/commands/questions/AddTfqCommand.java

Add whitespace in AddTfqCommand message usage

---

src/main/java/seedu/smartnus/logic/commands/quiz/NextQuestionCommand.java
src/main/java/seedu/smartnus/logic/commands/quiz/PrevQuestionCommand.java
src/main/java/seedu/smartnus/logic/commands/quiz/QuizCommand.java
src/main/java/seedu/smartnus/model/question/comparator/QuestionsDefaultComparator.java
src/test/java/seedu/smartnus/logic/parser/QuizCommandParserTest.java

Resolves some TODOs in some quiz commands

Resolve TODOs for equals method in quiz commands

---

src/main/java/seedu/smartnus/logic/commands/StatCommand.java
src/main/java/seedu/smartnus/logic/parser/StatCommandParser.java
src/test/java/seedu/smartnus/logic/commands/CommandTestUtil.java
src/test/java/seedu/smartnus/logic/commands/StatCommandTest.java
src/test/java/seedu/smartnus/logic/parser/StatCommandParserTest.java
src/test/java/seedu/smartnus/testutil/QuestionBuilder.java
src/test/java/seedu/smartnus/testutil/TypicalQuestions.java

Resolves #188 and #112
When user enters any text after the command, it will result in an error message with message usage
If user does not enter any text, it will show all stats instead

Modify stat command

---

src/main/resources/view/LightExtensions.css

Resolve PE-D color issue by using a more noticeable shade of red.
Resolves https://github.com/AY2122S1-CS2103T-F12-1/tp/issues/153

Modify error text color

---

docs/UserGuide.md
src/main/java/seedu/smartnus/model/question/ShortAnswerQuestion.java

Fix issues pointed out in PE-D

Fix PE-D issues

---

src/test/java/seedu/smartnus/logic/LogicManagerTest.java
src/test/java/seedu/smartnus/logic/commands/CommandTestUtil.java
src/test/java/seedu/smartnus/logic/commands/EditCommandTest.java
src/test/java/seedu/smartnus/logic/commands/EditQuestionDescriptorTest.java
src/test/java/seedu/smartnus/logic/commands/StatCommandTest.java
src/test/java/seedu/smartnus/logic/parser/AddMcqCommandParserTest.java
src/test/java/seedu/smartnus/logic/parser/AddSaqCommandParserTest.java
src/test/java/seedu/smartnus/logic/parser/AddTfCommandParserTest.java
src/test/java/seedu/smartnus/logic/parser/EditCommandParserTest.java
src/test/java/seedu/smartnus/logic/parser/QuizInputParserTest.java
src/test/java/seedu/smartnus/logic/parser/StatCommandParserTest.java
src/test/java/seedu/smartnus/model/ModelManagerTest.java
src/test/java/seedu/smartnus/model/SmartNusTest.java
src/test/java/seedu/smartnus/model/question/QuestionTest.java
src/test/java/seedu/smartnus/model/question/UniqueQuestionListTest.java
src/test/java/seedu/smartnus/model/quiz/QuizTest.java
src/test/java/seedu/smartnus/storage/JsonAdaptedQuestionTest.java
src/test/java/seedu/smartnus/storage/JsonSmartNusStorageTest.java
src/test/java/seedu/smartnus/testutil/TypicalQuestions.java
src/test/java/seedu/smartnus/testutil/TypicalQuiz.java

Change TypicalQuestions to proper questions

---

docs/UserGuide.md
src/main/java/seedu/smartnus/commons/core/Messages.java
src/main/java/seedu/smartnus/logic/commands/DeleteCommand.java
src/main/java/seedu/smartnus/logic/parser/DeleteCommandParser.java

Fixed all delete command error messages

---

src/main/java/seedu/smartnus/logic/commands/AddNoteCommand.java
src/main/java/seedu/smartnus/logic/parser/StatCommandParser.java
src/main/java/seedu/smartnus/model/Model.java
src/main/java/seedu/smartnus/model/ModelManager.java
src/main/java/seedu/smartnus/model/SmartNus.java
src/main/java/seedu/smartnus/model/note/Note.java
src/main/java/seedu/smartnus/model/note/NoteList.java
src/main/java/seedu/smartnus/model/note/exceptions/DuplicateNoteException.java
src/main/java/seedu/smartnus/model/note/exceptions/NoteNotFoundException.java
src/main/java/seedu/smartnus/model/question/Question.java
src/main/java/seedu/smartnus/storage/JsonAdaptedNote.java
src/test/java/seedu/smartnus/logic/commands/AddMcqCommandTest.java
src/test/java/seedu/smartnus/logic/commands/AddNoteCommandTest.java
src/test/java/seedu/smartnus/logic/commands/FindCommandTest.java
src/test/java/seedu/smartnus/logic/parser/AddNoteCommandParserTest.java

Resolved as many Todos as I could.
Need to add a couple of tests to resolve more.
The UI todos need to be resolved by someone who worked on the `Quiz` and the `Question` classes.

Resolve Todos

---

docs/team/abhishekgupta.md

Merge this pls.
Hopefully before the deadline.

Abhishek PPP

---

docs/DeveloperGuide.md

For some reason there was a duplicate quiz implementation after my previous pr, this removes it

Remove duplicate quiz implementation

---

src/main/java/seedu/smartnus/logic/commands/quiz/NextQuestionCommand.java
src/main/java/seedu/smartnus/logic/commands/quiz/PrevQuestionCommand.java

Changed from `Got Next Question!` to `Got the Next Question`

update quiz navigation output

---

docs/UserGuide.md

Add add a question section

---

docs/DeveloperGuide.md

Removed quiz parsing section that I forgot to remove earlier

Removed quiz parsing section
